apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarot-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarot-frontend
  template:
    metadata:
      labels:
        app: tarot-frontend
    spec:
      containers:
      - name: tarot-frontend
        image: bufstudio/tarot-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://tarotmate-backend-service:5000"
        - name: NEXT_PUBLIC_COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: aws-cognito-secrets
              key: user-pool-id
        - name: NEXT_PUBLIC_COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: aws-cognito-secrets
              key: client-id